# Generated by Django 2.2.7 on 2019-12-03 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['nome', 'ano_lancamento'], 'verbose_name': 'Anime'},
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nome', 'sobrenome'], 'verbose_name': 'Autor'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome_categoria'], 'verbose_name': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['situacao'], 'verbose_name': 'Status'},
        ),
    ]
