# Generated by Django 2.2.7 on 2019-12-04 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191203_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['nome'], 'verbose_name': 'Anime'},
        ),
    ]
