# Generated by Django 2.2.7 on 2019-12-04 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191203_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['nome', 'ano_lancamento'], 'verbose_name': 'Anime'},
        ),
    ]
